import Head from "next/head";
import Image from "next/image";
import Nav from "../component/Nav";
import Header from "../component/Header";

export default function Home() {
  return (
    <div className="gradient-bg-services pt-3">
      <Head>
        <title>Blog Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="gradient-bg-welcome">
        <Nav/>
        <Header/>
      </div>
    </div>
  );
}
